services:
  binaries:
      build:
        dockerfile: Dockerfile
        secrets:
          - WIFI_SSID
          - WIFI_PASS
      user: "${UID:-1000}:${GID:-1000}"
      volumes:
        - type: bind 
          source: ./artifacts/docker
          target: /artifacts-bind
          read_only: false
  server:
      build:
        context: server
      volumes:
        - type: bind 
          source: ./artifacts/docker
          target: /artifacts-bind
          read_only: false
secrets:
  WIFI_SSID:
    environment: WIFI_SSID
  WIFI_PASS:
    environment: WIFI_PASS
