services:
  build:
      build:
        dockerfile: Dockerfile
      user: "${UID:-1000}:${GID:-1000}"
      volumes:
        - type: bind 
          source: ./artifacts/docker
          target: /artifacts-bind
          read_only: false
      command: sh -c "mkdir -p /artifacts-bind && cp -r /artifacts/* /artifacts-bind"
