arch := "arm-none-linux-gnueabihf"
gcc := arch + "-gcc"
artifacts_dir := "../artifacts/"

build-all: helloworld-build
watch-all:
  just helloworld-watch

helloworld-build: (_build "1-hello-world")

helloworld-watch: (_watch "1-hello-world")

_watch PROJECT:
  watchexec --postpone --wrap-process session --verbose -e c,h -w ./{{PROJECT}} -- just _build \"{{PROJECT}}\"

_build PROJECT:
  {{gcc}} ./{{PROJECT}}/*.c -O3 -o ../artifacts/{{PROJECT}}-c

