artifacts_dir := "../artifacts/"

build-all: helloworld-build
watch-all:
  just helloworld-watch

helloworld-build: (_build "1-hello-world")

helloworld-watch: (_watch "1-hello-world")

_watch PROJECT:
  watchexec --postpone --wrap-process session --verbose \
  -e c,h -w ./{{PROJECT}} --on-busy-update=restart \
  -- just _build \"{{PROJECT}}\"

_build PROJECT:
  mkdir -p build && cd build && cmake .. && make {{PROJECT}}-c \
  && cp ./bin/{{PROJECT}}-c ../{{artifacts_dir}}/{{PROJECT}}-c

