[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = [
  "--cfg",
  "espidf_time64",
  "--cfg",
  "esp_idf_comp_esp_adc_enabled",
  "--cfg",
  "esp_idf_comp_espressif__mdns_enabled",
]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.4"
